import type { CommerceProduct } from "@/game/shop/types";

export const fifthDawnCatalog: CommerceProduct[] = [
  {
    id: "fd_founders_pack",
    platformProductId: "fd_founders_pack",
    title: "파운더 팩",
    summary: "초기 후원자를 위한 정체성 보상과 상징 장식 세트입니다.",
    category: "founder",
    type: "non-consumable",
    fairUseNote: "정체성 장식과 소규모 시작 보너스만 제공합니다. 전투 우위나 승천 자격은 판매하지 않습니다.",
    unlockPreview: ["파운더 칭호와 배지", "프로필 프레임과 배너 장식", "정착지 장식물: 파운더 배너, 파운더 첨탑", "초기 공명 포인트 소량 보너스"],
    unlocks: {
      settlementObjectTypes: ["founder-banner", "founder-spire"],
      settlementThemes: [],
      profileTitles: ["여명의 개척자"],
      profileBadges: ["파운더 배지"],
      profileFrames: ["파운더 프레임"],
      beaconSkins: [],
      starterBonusResonance: 8,
    },
  },
  {
    id: "fd_starter_pack_01",
    platformProductId: "fd_starter_pack_01",
    title: "스타터 팩 01",
    summary: "초기 정착지 정비에 도움이 되는 안전한 시작 꾸미기 팩입니다.",
    category: "starter",
    type: "non-consumable",
    fairUseNote: "초반 정착지 세팅 편의만 보강합니다. 진행을 무너뜨리는 강한 파워는 포함하지 않습니다.",
    unlockPreview: ["정착지 장식물: 새벽 상자, 스타터 램프", "초보자용 장식 배치 선택지 확장", "초기 공명 포인트 소량 보너스"],
    unlocks: {
      settlementObjectTypes: ["dawn-crate", "starter-lamp"],
      settlementThemes: [],
      profileTitles: [],
      profileBadges: [],
      profileFrames: [],
      beaconSkins: [],
      starterBonusResonance: 5,
    },
  },
  {
    id: "fd_building_pack_luminous_garden",
    platformProductId: "fd_building_pack_luminous_garden",
    title: "빛정원 건축 팩",
    summary: "정화 정원과 회복형 정착지를 꾸밀 수 있는 빛정원 팔레트입니다.",
    category: "building",
    type: "non-consumable",
    fairUseNote: "정착지 미관과 테마를 확장하는 장식 팩입니다. 경쟁 우위를 직접 판매하지 않습니다.",
    unlockPreview: ["정착지 테마: 빛정원", "정착지 장식물: 빛의 아치, 정원 비콘", "정원형 산책로와 회복 공간 연출"],
    unlocks: {
      settlementObjectTypes: ["luminous-arch", "garden-beacon", "garden-bed", "flower", "lamp"],
      settlementThemes: ["luminous-garden"],
      profileTitles: [],
      profileBadges: [],
      profileFrames: [],
      beaconSkins: [],
      starterBonusResonance: 0,
    },
  },
  {
    id: "fd_building_pack_star_hub",
    platformProductId: "fd_building_pack_star_hub",
    title: "스타 허브 건축 팩",
    summary: "차후 관문과 허브 광장으로 이어질 중심 광장 계열 정착지 팩입니다.",
    category: "building",
    type: "non-consumable",
    fairUseNote: "허브·광장·관문 장식만 제공합니다. 외교 성공이나 영토 우위 같은 승부 요소는 판매하지 않습니다.",
    unlockPreview: ["정착지 테마: 스타 허브 프라임", "정착지 장식물: 스타 게이트, 포털 첨탑, 허브 광장", "차후 5D 허브 확장과 호환되는 광장 미학"],
    unlocks: {
      settlementObjectTypes: ["star-gate", "portal-spire", "hub-plaza", "tower", "sign"],
      settlementThemes: ["star-hub-prime"],
      profileTitles: [],
      profileBadges: [],
      profileFrames: [],
      beaconSkins: [],
      starterBonusResonance: 0,
    },
  },
  {
    id: "fd_residence_pack_origin_home",
    platformProductId: "fd_residence_pack_origin_home",
    title: "기원 거처 팩",
    summary: "고요한 기원 거주지 느낌을 살리는 주거 전용 테마 팩입니다.",
    category: "residence",
    type: "non-consumable",
    fairUseNote: "주거 외형과 내부 장식 위주입니다. 능력치를 직접 판매하지 않습니다.",
    unlockPreview: ["정착지 테마: 기원 거처", "정착지 장식물: 기원 스크린, 기원 침대", "향후 다중 거주지 시스템과 호환되는 주거 스킨"],
    unlocks: {
      settlementObjectTypes: ["origin-screen", "origin-bed", "floor", "bench"],
      settlementThemes: ["origin-home"],
      profileTitles: [],
      profileBadges: [],
      profileFrames: [],
      beaconSkins: [],
      starterBonusResonance: 0,
    },
  },
  {
    id: "fd_cosmetic_pack_dawn_beacons",
    platformProductId: "fd_cosmetic_pack_dawn_beacons",
    title: "새벽 비콘 코스메틱 팩",
    summary: "비콘과 프로필 표현을 꾸미는 순수 코스메틱 팩입니다.",
    category: "cosmetic",
    type: "non-consumable",
    fairUseNote: "연출용 스킨과 프로필 꾸미기만 제공합니다. 게임 진행 우위는 주지 않습니다.",
    unlockPreview: ["비콘 스킨: 새벽 비콘", "프로필 장식과 정체성 표현 요소", "정착지 조명 연출용 미학 강화"],
    unlocks: {
      settlementObjectTypes: [],
      settlementThemes: [],
      profileTitles: ["비콘 감시자"],
      profileBadges: ["새벽 비콘 문장"],
      profileFrames: ["비콘 광륜 프레임"],
      beaconSkins: ["dawn-beacon"],
      starterBonusResonance: 0,
    },
  },
];
